[package]
name = "repository-storage"
version = "0.1.0"
description = "Solana program for storing repository metadata"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "~1.16.0"
borsh = "0.10.3"
borsh-derive = "0.10.3"

[features]
no-entrypoint = []